### ISSUE TITLE
not printing the output information of the optimization process?

### ISSUE THREAD

**Issue by ShabnamR** [peterdsharpe/Falkner-Skan#1]
Hi, 

I have been using parts of the code for a curve fitting algorithm and I was wondering is there any way to stop the printing of the optimization process in the terminal as the code is running? I have gone through the code and cannot figure out where this printing is happening. Can you direct me to the place to turn it off or maybe re-route it to a txt file?

**Comment by peterdsharpe** [comment]
Hi @ShabnamR,

Yes, this is possible! Use the verbose argument of `Opti`'s `solve()` method:

```python
import aerosandbox as asb
opti = asb.Opti()
...
sol = opti.solve(verbose=False)
```

**Comment by peterdsharpe** [comment]
P.S. You may also consider the use of `aerosandbox.FittedModel`, which includes some nice curve fitting features.

Documentation/source: https://github.com/peterdsharpe/AeroSandbox/blob/develop/aerosandbox/modeling/fitting.py

Examples: https://github.com/peterdsharpe/AeroSandbox/tree/develop/aerosandbox/modeling/test_modeling
